# Generated by Django 5.2.4 on 2025-08-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0003_alter_book_options"),
    ]

    operations = []
